language: ruby
env:
  global:
    - SHARED=OFF
    - BUILD_DEPENDENCY_FROM_SOURCE=OFF
    - NPROC=2

notifications:
  email:
    on_success: never
    on_failure: always

matrix:

  include:
    # Style check only
    - os: linux
      dist: trusty
      sudo: true
      language: python
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - gcc-4.9
            - g++-4.9
            - cmake-data # to use cmake 3.0 or more recent
            - cmake
            - clang-format-5.0
      env: CC='gcc-4.9' CXX='g++-4.9'
      before_install: ./util/scripts/setup-linux.sh
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make check-style

    # Default environment of Ubuntu 14.04
    - os: linux
      dist: trusty
      sudo: true
      language: python
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - cmake-data # to use cmake 3.0 or more recent
            - cmake
      env: CC='gcc-4.9' CXX='g++-4.9'
      before_install: ./util/scripts/setup-linux.sh
      script: ./util/scripts/run-travis.sh

    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - cmake-data # to use cmake 3.0 or more recent
            - cmake
      env: SHARED=ON CC='gcc-4.9' CXX='g++-4.9'
      before_install: ./util/scripts/setup-linux.sh
      script: ./util/scripts/run-travis.sh

    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - cmake-data # to use cmake 3.0 or more recent
            - cmake
      env: BUILD_DEPENDENCY_FROM_SOURCE=ON CC='gcc-4.9' CXX='g++-4.9'
      before_install: ./util/scripts/setup-linux.sh
      script: ./util/scripts/run-travis.sh

    # Similar environment of Ubuntu 16.04 (gcc 5.4)
    # travis ci only supports Ubuntu 14.04 (trusty) gcc-5 and 6
    # another option is to use docker.
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake-data # to use cmake 3.0 or more recent
            - cmake
      env: BUILD_DEPENDENCY_FROM_SOURCE=ON CC='gcc-6' CXX='g++-6'
      before_install: ./util/scripts/setup-linux.sh
      script: ./util/scripts/run-travis.sh

    # Default environment of macOS 10.13 High Sierra
    # compiled using clang shipped with xcode10.1
    - os: osx
      osx_image: xcode10.1
      script: travis_wait 30 ./util/scripts/run-travis.sh
      before_install: ./util/scripts/setup-osx.sh

    - os: osx
      osx_image: xcode10.1
      env: BUILD_DEPENDENCY_FROM_SOURCE=ON
      script: travis_wait 30 ./util/scripts/run-travis.sh
      before_install: ./util/scripts/setup-osx.sh

    - env: DOCKER=YES UBUNTU=16.04 BUNDLE=deps ENV=py3 LINK=STATIC
      script: ./util/docker/open3d-test/tools/test.sh $UBUNTU $BUNDLE $ENV $LINK
      before_install: sudo apt-get update && sudo apt-get install -y realpath

    - env: DOCKER=YES UBUNTU=16.04 BUNDLE=deps ENV=py3 LINK=SHARED
      script: ./util/docker/open3d-test/tools/test.sh $UBUNTU $BUNDLE $ENV $LINK
      before_install: sudo apt-get update && sudo apt-get install -y realpath
